version: 2.1

jobs:
  build-test:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm test

worflows:
  buildtest:
    jobs:
      -build-test:
        filters:
          branches:
            only:
              - circleci