name: Test Workflow

on:
  push:
    branches:
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: Test the application
        run: |
          npm test


  deploy:
    runs-on: ubuntu-latest

    needs: build-test

    steps:
      - uses: actions/checkout@v3

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "6727a74b-6842-416e-9de4-424ab94f90f9"
          heroku_app_name: "joke-app-iw3" #Must be unique in Heroku
          heroku_email: "mohammadamine.banaei@protonmail.com"

      - name: Log into registry ${{ env.REGISTRY }}
          if: github.event_name != 'pull_request'
          uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: "dckr_pat_2qW3V85yY1bfzDbCd-PvZBOQPj0"

      - name: Build and push Docker image
          id: build-and-push
          uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
          with:
            context: .
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}